latency_budget_ms: 300
reward_cooldown_s: 3
weights: {stimulus: 0.40, confidence: 0.30, reward_bias: 0.20, mood: 0.10}
commands_map:
  сидіти: SIT
  лежати: LIE_DOWN
  до_мене: COME
  голос: BARK
reward_triggers: {SIT: true, LIE_DOWN: true, COME: true, BARK: false}
mood_initial: CALM
tts:
  provider: gtts
  language: uk
  voice: com.ua
