name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -U pip
      - run: pip install -r requirements-dev.txt
      - run: pip install -e .[dev]
      - run: pytest -q
